### ISSUE TITLE
 landmarks are converted to 62.5 frames per second

### ISSUE THREAD

**Issue by old-fan-kk** [yzhou359/MakeItTalkNet#3]
Hi, thank you for sharing this code.
How do you use interpolation to convert landmarks to 62.5 frames per second?
your reply will vary appreciated!

**Comment by yzhou359** [comment]
We simply use linear interpolation to convert all video to the same 62.5 fps.

**Comment by old-fan-kk** [comment]
Thank you very much for your reply. 
Excuse me, is there this function in your code? I did not find this function

**Comment by yzhou359** [comment]
It's in our data preparation codebase. You can try this function:
```
def interp_func(input_mat, src_fps=25, trg_fps=62.5):
    xp = list(np.arange(0, input_mat.shape[0], 1))
    interp_xp = list(np.arange(0, input_mat.shape[0], src_fps/trg_fps))
    interp_mat = np.zeros(shape=(len(interp_xp), input_mat.shape[1]))
    for j in range(input_mat.shape[1]):
        interp_mat[:, j] = np.interp(interp_xp, xp, input_mat[:, j])
    return interp_mat
```

**Comment by old-fan-kk** [comment]
Thank you very much for your reply!!!
